[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-alpine-linux-musl-gcc"
rustflags = ["-C", "target-feature=-crt-static"]
[target.arm-unknown-linux-musleabihf]
rustflags = ["-C", "target-feature=-crt-static"]
